### ISSUE TITLE
Verificação antes de publicar

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#105]
CMs, localização e movimentação devem ser colocados antes de ser publicado o sinal.
Ao mudar o status para publicado e salvar essas verificações devem ser feitas.
Sinal já publicado, se for editado não pode ser salvo sem as CMs, localização e movimento.

**Comment by BryanMLima** [comment]
Quando o checkbox publicado for selecionado, é obrigatorio selecionar os sinais, localização e movimento. Mesmo que o sinal não possua.
