### ISSUE TITLE
Form sinal admin

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#107]
Quando um sinal é criado sem as CMs, depois ao tentar editar ele não permite mudar.

**Comment by ramonrdm** [comment]
Corrigido, agora é sempre possível trocar.
Mas falta:
- [ ] trocar o "None" por outra null ou '', senao não consigo deixar vazio ao tentar editar.
- [ ] imagem localização fica como indefinida e não mostra nada.

**Comment by BryanMLima** [comment]
É possível deixar vazio ao editar agora, troquei a imagem para apenas o X quando for selecionado o vazio pelo usuario.
