### ISSUE TITLE
Busca por glossário

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#109]
Ao escolher um glossário na index a busca deve se limitar a esse glossário.
- [ ] Busca por um glossário
- [ ] Deixar evidente na tela que está sendo buscado somente em um glossário
- [ ] Possibilidade de limpar filtros de busca e o glossário tbm
- [ ] Identificar na exibição do sinal o glossário

**Comment by BryanMLima** [comment]
![image](https://user-images.githubusercontent.com/42067040/90799695-f8581180-e2e9-11ea-923d-da526765ec0b.png)
