### ISSUE TITLE
Formas de criar um usuário customizado para o django

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#11]
Formas de criar um usuário customizado para o django 1.10, como está agora serve? o Profile de user djando como usar? precisamos ter usename, senha, nome completo, lattes, foto, e-mail.

**Comment by thiagobrez** [comment]
Depende do propósito do usuário:
- **Proxy Model**: se não precisar guardar informações extras sobre o usuário no banco de dados, somente criar novos métodos;
- **User Profile**: se você está contente com a autenticação feita pelo django e quer adicionar atributos não relacionados a esta;
- **AbstractBaseUser**: se você não está contente com a autenticação feita pelo django;
- **AbstractUser**: se você está contente com a autenticação feita pelo django, mas mesmo assim quer adicionar atributos sem ter que criar um Model separado.

> ...precisamos ter usename, senha, nome completo, lattes, foto, e-mail.

Me parece que a melhor opção seria o User Profile, visto que o username e a senha já são gerenciados pelo django.auth. Nome completo, lattes, foto e e-mail são atributos que não interferem na autenticação.

A implementação pode ser feita facilmente seguindo este link: [https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone](url)

**Comment by thiagobrez** [comment]
Consegui fazer funcionar o user profile em um novo projeto, mas no glossário ainda está dando conflito...trabalhando em cima disso.

**Comment by thiagobrez** [comment]
Concluído, agora consertando alguns bugs em torno disso.

**Comment by thiagobrez** [comment]
Concluído.
