### ISSUE TITLE
Mostrar quantidade de sinais

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#110]
- [x] Indicar total de sinais publicados na index
- [x] Indicar no ícone de cada glossário a quantidade
- [x] Indicar dentro de cada glossário a quantidade de sinais publicados

**Comment by BryanMLima** [comment]
Com o número total acho que o design fica estranho. Não tive nenhuma ideia que mostrasse de um jeito bom.
![num_sinais_com_total](https://user-images.githubusercontent.com/42067040/91579731-6f149080-e922-11ea-84fe-bc6372b98972.png)

Sem o numero total fica assim:
![num_sinais_sem_total](https://user-images.githubusercontent.com/42067040/91579899-ad11b480-e922-11ea-825d-a65cb88a99ab.png)
