### ISSUE TITLE
Preview do sinal com imagens

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#113]
O preview visual do sinal deve ser uma transição de 4 imagens, que serão retiradas do vídeo do sinal,  um frame a cada tempo/4. Hoje o vídeo está travando toda a exibição.
- [x] retirar 4 frames via ffmpeg ao postar ou editar um video do sinal
- [x] armazenar os 4 frames na variável do sinal (ver a melhor forma pra fazer isso mas deve ser dentro do sinal)
- [x] Substituir nas listas onde mostram os sinais e o preview, agora deve aparecer a thumb como o frame 2 e ao deixar o mouse em cima passar a sequencia de 4 imagens repetidamente.
- [x] estudar a possibilidade de fazer um gif... pode ficar pesado e ruim tbm

**Comment by BryanMLima** [comment]
A geração dos frames foi feita junto a atualização das paths dos videos depois de convertidos.
