### ISSUE TITLE
Estudar lib arbor

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#12]
Estudar lib arbor e direcionar o clique de um tema para uma lista de sinais do tema, onde cada sinal pode ser novamente clicado e exibido.

**Comment by HanichS** [comment]
Alguns links interessantes encontrados: 

- http://blog.thinkst.com/2011/06/simple-graphs-with-arborjs.html

- http://jsfiddle.net/JapkX/89/

- http://arborjs.org/reference

- https://github.com/samizdatco/arbor (em demos/atlas/atlas.js existe uma função resize que deixa ele responsivo)

Eu segui a risca o primeiro link na página temas.html, mas mesmo assim ainda não apareceu nenhum node.

Continuo na busca da solução.

**Comment by thiagobrez** [comment]
Também fiz algumas tentativas, e meu palpite é que o problema está relacionado com a view temas, quando esta chama a função criaNodo, na parte em que é criado um nodo com base no filtro dos temas existentes (foto). Apesar de termos mexido nas importações da biblioteca, creio que não seja lá o problema, visto que antes de começarmos a alterar o documento existia um nodo na página.

![ss1](https://user-images.githubusercontent.com/26878038/27083318-8fa6040a-501e-11e7-95f8-5c7e7401a69d.png)

O texto marcado na foto mostra um filtro por id do tema, mas se tem vários, como não encontra nenhum? E porquê id=1?

**Comment by HanichS** [comment]
Conforme nós vimos com o Ramon, o problema é solucionado trocando **id=1** por **temaPai=None** na linha 99 e na 128.

**Comment by thiagobrez** [comment]
Issue reaberta pois não foi totalmente concluída, falta encontrar maneira de redirecionar para a página de sinais do tema ao clicar no nodo.

**Comment by thiagobrez** [comment]
Pode ser que haja uma substituição da biblioteca, conforme conversado com @ramonrdm. A melhor opção parece que é o D3, mas ainda não sei se vai atender às nossas necessidades.

**Comment by BryanMLima** [comment]
http://asl-lex.org/
outra referencia para arvore de busca
