### ISSUE TITLE
Populate inicial do projeto

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#16]
Analisar e pesquisar como utilizar um conjuntos de dados inicial para o projeto, usando um populate do django. Desta forma nos economiza trabalho na hora de criar um novo projeto. Acho que tem como alinhar isso com o migrate. pesquisem e implementem.

**Comment by thiagobrez** [comment]
Criado diretório fixtures/fixtures.json para popular o banco de dados. Ainda não está funcional devido à maneira como devem ser referenciados foreignKeys. Commit d27859de6cfab5ffa69e798ce81c6842b9448eec

**Comment by thiagobrez** [comment]
Dumpdata do meu banco de dados local realizado sobre o arquivo fixtures/data_dump.json. Se necessário realizar o populate, chamar o comando ./manage.py loaddata data_dump.json.

**Comment by ramonrdm** [comment]
Ótimo!
só coloca isso no arquivo de readme, no final em uma nova sessão, "procedimentos", então você coloca ali como fazer o migrate e populate. apos isso fechar a issue novamente.

**Comment by thiagobrez** [comment]
Feito!
