### ISSUE TITLE
Mostrar nome correto da instancia nas listas

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#19]
Vocês perceberão que qndo fizerem uma instancia nova ela irá ficar nas listagens ou menus dropdown com a mesma indentificação algo do tipo "objetc...", para consertar isso devem colocar dentro do modelo algo como:
def __unicode__(self):
		return self.numeroContrato + " - " + self.nome
não tenho certeza como o django 1.10 faz isso, mas antes fazia assim.

**Comment by thiagobrez** [comment]
Corrigido 6 dias atrás no  db2b9d97bdd75688b519d0c748946f45b68e963f

**Comment by thiagobrez** [comment]
Verificar se está da maneira desejada. Por exemplo, no admin, ao criar uma configuração de mão, ela aparecerá somente como "Configuração de mão", não como "Configuração de mão numero_da_configuração".

**Comment by thiagobrez** [comment]
Alterar nome das instâncias das CM e grupoCM para que na página sinal seja exibido corretamente. Corrigir o nome da localização que ainda não foi corrigido.

**Comment by thiagobrez** [comment]
Nome da localização já foi corrigido alguns commits atrás.

**Comment by HanichS** [comment]
Conforme vismos com o Ramon: 

- Issue concluída;

- No template sinal deve aparecer somente imagem.

**Comment by thiagobrez** [comment]
Concluído.
