### ISSUE TITLE
Estudar e analisar Glossário Letras Libras

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#2]
Ler história:
http://glossario.libras.ufsc.br/index/historia
usar o glossário para fazer buscas e analisar funcionamento da ferramenta:
glossario.libras.ufsc.br
fazer buscas, verificar resultados.

**Comment by ramonrdm** [comment]
baixem o código aqui também e façam rodar.
Acho que ta usando a versão 1.7 e 1.8 pra funcionar.
Podem fazer funcionar na 1.10, usem uma virtual env para usar py 2.7 e django 1.10.

**Comment by thiagobrez** [comment]
Funcionando.
