### ISSUE TITLE
Separar códigos css por template

### ISSUE THREAD

**Issue by thiagobrez** [ramonrdm/glossariolibras#21]
- Atualmente está tudo no base.css; separar por template;
- Remover códigos não mais utilizados.

**Comment by thiagobrez** [comment]
Refatoração dos códigos css iniciada para melhor entendimento das classes.

**Comment by thiagobrez** [comment]
Avaliar a possibilidade de deixar tudo no base.css e separar as classes por template com comentários (como já está sendo feito). Me parece uma boa ideia também.

![screenshot from 2017-06-08 11-05-43](https://user-images.githubusercontent.com/26878038/26932646-7153ef36-4c3a-11e7-8d95-7e751ba18847.png)

**Comment by ramonrdm** [comment]
deletar indexmateria e style

**Comment by HanichS** [comment]
Conforme vimos com o Ramon:

- Criar um css para pesquisa;

- Criar css para página de sinal.

**Comment by thiagobrez** [comment]
Concluído. Commits dbb38da1db6357d3e29c138da73b72845ea8179e e 154721b7913548b4dbbe7aa0be578c1c3c9b0770.
