### ISSUE TITLE
Criar uma nova página de teste e começar do zero, sem ctrl c + ctrl v

### ISSUE THREAD

**Issue by HanichS** [ramonrdm/glossariolibras#24]
Criar nova página sinal.html conforme especificações do título.

**Comment by thiagobrez** [comment]
Alguém poderia me relembrar o motivo desta issue?

**Comment by HanichS** [comment]
Posso estar enganada, mas pelo que lembro era porque a página tinha aquele erro de não extender muito bem o base.

**Comment by HanichS** [comment]
Criei a página sinal_teste.html para realizarmos os testes. A princípio não está funcionando.

**Comment by thiagobrez** [comment]
Isso! Valeu! Vou tentar dar uma olhada também.

**Comment by thiagobrez** [comment]
Corrigido! commit 5cfe713. O problema era a importação do js do materialize que estava sendo feita de maneira errada no baseSearchNav.html.
