### ISSUE TITLE
Abas vídeos do termo

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#31]
Cada sinal/termo tem vídeos, eu os coloquei em abas usando somente o jquery.
Mas deixei o layout e centralização para vocês ajustarem.

**Comment by thiagobrez** [comment]
Concluído, falta somente encontrar maneira de que as abas ocupem toda a extensão da tela. Por algum motivo a class "row" está bugando isso.

**Comment by thiagobrez** [comment]
Concluído, commit 8d3c124. Parece estar funcionando corretamente no chrome, mas no safari não.
