### ISSUE TITLE
persistencia do formulário de busca

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#32]
fazer a persistência entre páginas do formulário e os dados buscados.

**Comment by thiagobrez** [comment]
Tentando implementar através do uso de cookie-based sessions.

**Comment by thiagobrez** [comment]
Persistência do formulário funcionando, mas agora a checkbox do inglês não aparece. Falta arrumar isso e replicar para o mobile.

**Comment by thiagobrez** [comment]
Corrigindo persistência ao trocar da página pesquisa para sinal.

**Comment by thiagobrez** [comment]
Persistência das checkboxes concluída.

**Comment by thiagobrez** [comment]
Persistência do formulário de busca removida para melhor experiência do usuário. A barra de busca do materialize só revelava o texto buscado quando clicava na barra novamente após a pesquisa, fazendo com que a segunda pesquisa fosse feita errada, pois o usuário pensou que não havia texto nenhum inserido.
