### ISSUE TITLE
Link portal Libras

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#34]
Esqueci de mencionar, precisamos de um link no menu principal para o portal Libras.
Temos o desafio de tornar navegável por todos os sistemas do Libras, sendo assim precisamos de pelo menos um link fixo no menu do glossário que leve ao portal libras.
libras.ufsc.br é o link

**Comment by thiagobrez** [comment]
Concluído. Commit 766feff.

![ss1](https://user-images.githubusercontent.com/26878038/27832820-7d0191e6-60a6-11e7-9088-b3a7a415a685.png)

**Comment by ramonrdm** [comment]
Poxa gostei da imagem, mas vamos usar só o texto mesmo "Portal Libras" ou "Portal Libras Libras" o que ficar melhor no menu.

**Comment by ramonrdm** [comment]
podes usar como icone a imagem das mãos apenas, ai sim pequeno igual os outros.

**Comment by thiagobrez** [comment]
Beleza!

**Comment by thiagobrez** [comment]
Corrigido. Inseri o logo do portal libras sem o texto como ícone do link na sidenav, mas a edição foi feita no gimp. Não é perceptível, mas pode haver alguma irregularidade no ícone pois utilizei a ferramenta de seleção automática do gimp. Então, quando for posto em produção, quem sabe seja bom pedir para os designers que fizeram o logo editarem melhor.

![ss1](https://user-images.githubusercontent.com/26878038/27862786-6c2637d4-615d-11e7-8bb4-1ceb6a00c0c3.png)
