### ISSUE TITLE
Pagina sinal, só uma localização

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#35]
Na página do sinal só a um localização e não duas.

**Comment by ramonrdm** [comment]
na transição de abas não precisa a cima do vídeo repetir o nome da aba.
Colocar o bsw(vai virar uma imagem), portugues e ingles logo a baixo do vídeo em um card, depois disso os cards de configuração de mão.

**Comment by thiagobrez** [comment]
O bsw acima do vídeo aparece em todas as abas?

**Comment by thiagobrez** [comment]
Concluída. Decidi colocar a descrição num card ao lado das traduções pois se juntasse parece que fica estranho, qualquer coisa posso reverter.

Imagem 1:
![ss1](https://user-images.githubusercontent.com/26878038/27829417-e86a24ca-6097-11e7-8440-409294c33400.png)

Imagem 2:
![ss2](https://user-images.githubusercontent.com/26878038/27829418-eaad002c-6097-11e7-82c9-066f0c338c03.png)

Imagem 3: A localização fica um pouco escondida pelo footer (a página está o mais para baixo possível)
![ss3](https://user-images.githubusercontent.com/26878038/27829419-eca90e02-6097-11e7-8183-2985b04040a5.png)

Imagem 4: Como ficaria sem o footer (a título de exemplo)
![ss4](https://user-images.githubusercontent.com/26878038/27829421-eeab28f2-6097-11e7-9f18-0dcb9c9b49f6.png)

**Comment by thiagobrez** [comment]
Retirei localização dos cards da mão, que havia esquecido, melhorei a responsividade da página.
