### ISSUE TITLE
Atualizar menu principal superior

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#4]
Colocar um novo menu utilizando o materializecss.

**Comment by thiagobrez** [comment]
Falta:
- Substituir o logo da ufsc pelo original e editar no photoshop;
- Evitar que os dois logos se colidam em devices menores;
- Corrigir a cor do navbar (a que está atualmente é próxima da original);
- Fazer o menu mobile funcionar;

**Comment by thiagobrez** [comment]
Menu mobile funcionando.

**Comment by thiagobrez** [comment]
- Adicionado dropdown do sidenav (menu mobile) para opções dos glossários. Verificar como fazer para n glossarios genéricos;
- Aprimorada aparência do sidenav;
- Encontrado erro que faz sidenav não abrir nas páginas de pesquisa;

**Comment by HanichS** [comment]
Navbar fixada.

**Comment by thiagobrez** [comment]
Tabs de extensão da navbar nos templates glossario.html e pesquisa.html parcialmente implementadas. Funcionando mas não da maneira esperada.

**Comment by thiagobrez** [comment]
Removidas tabs. Implementado sidenav fixa.

**Comment by thiagobrez** [comment]
Menu superior (navbar) substituído pelo menu lateral (sidenav). Agora só haverá menu superior em telas média e pequenas. Ordem dos ícones da sidenav alterada para melhor experiência do usuário. Retirado ícone do admin pois pareceu desnecessário para o usuário final, os desenvolvedores ainda podem acessá-lo pelo url /admin.

**Comment by thiagobrez** [comment]
Search bar implementada na sidenav dos glossários, mas ainda não está funcional (verificar como linkar este form de busca com o do Django via jQuery). Corrigidos alguns erros de apresentação da sidenav.

**Comment by thiagobrez** [comment]
Verificar uma maneira melhor de apresentar a sidenav dos glossários, pois está por cima da sidenav base, o que pode provocar que o carregamento seja mais lento. Verificar como extender a sidenav mobile, pois no glossário também precisa ser alterada e como o base já possui uma, se outra for inserida, fica duplicada.

**Comment by thiagobrez** [comment]
Adicionados ícones aos links das sidenavs.

**Comment by thiagobrez** [comment]
Agora existem dois templates base, um para as templates que necessitam da sidenav padrão e outro para as que necessitam da sidenav com searchbar (glossario, pesquisa e sinal). Assim, está corrigido os problemas de duplicação de navs, estão sendo apresentados da maneira correta. Verificar o mapeamento de url da página sinal.html, parece que faz com que a imagem do glossário não carregue.

**Comment by thiagobrez** [comment]
Verificar como corrigir as imagens da sidenav mobile que "ativam" ao dar hover com o mouse.

**Comment by thiagobrez** [comment]
Mecanismo de busca funcionando corretamente na sidenav nos tres templates que o utilizam, glossario.html, sinal.html e pesquisa.html. Falta arrumar logica da view sinal pois ao entrar no sinal ele nao e exibido.

(Procurar saber porque os acentos do meu teclado pararam de funcionar???)

**Comment by thiagobrez** [comment]
Verificar porque que a sidenav não abre em algumas páginas. Corrigir as imagens da sidenav mobile que "piscam" quando hoveradas como se fossem botões.

**Comment by thiagobrez** [comment]
A página sinal.html é a única que não funciona o javascript de abrir o sidenav mobile e o css (materialize) de efeito de onda nos botões da sidenav. Porquê, se ela extende a baseSearchNav igual ao glossario.html ou pesquisa.html?
