### ISSUE TITLE
Chrome - página inicial do glossário

### ISSUE THREAD

**Issue by thiagobrez** [ramonrdm/glossariolibras#41]
Ná página inicial do glossário no chrome, não é possível iniciar o vídeo porque o player do navegador só permite iniciar clicando no botão (não em cima do vídeo) e o botão está escondido pelo footer (montanhas verdes). Também no chrome, não é possível avançar o vídeo para qualquer posição.

**Comment by thiagobrez** [comment]
O player do chrome também permite que o usuário baixe o vídeo, isso é bom? Bloquear essa função?

**Comment by ramonrdm** [comment]
layout mudou agora tem essa opção ;)
