### ISSUE TITLE
centralizar e limintar tamenho video do glossário

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#5]
glossario.html

**Comment by thiagobrez** [comment]
Transportar o menu antigo para o materialize (extensão da sidenav)

**Comment by ramonrdm** [comment]
usar o video responsivo tbm

**Comment by thiagobrez** [comment]
Concluído.

**Comment by thiagobrez** [comment]
Ajustada posição, tamanho e frame do vídeo do glossário. Retirados botões pois o player já possui e estava redundante.
