### ISSUE TITLE
Avatar de localização

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#52]
Copiar o código e imagens do avatar de localização e usar no formulário atual do sinal.
podes dar um include js no form
o campo de localização pode ficar oculto e vc pode colocar uma figura da localização qndo a mesma for selecionada no avatar.
as localizações se mantêm iguais ao do sistema em produção.

**Comment by thiagobrez** [comment]
Começando a implementação utilizando o plugin Image Mapster.

**Comment by thiagobrez** [comment]
Quase concluído, falta adicionar as coordenadas corretas, terminar a sincronização do imagepicker com a área selecionada e alguns bugs visuais.

**Comment by thiagobrez** [comment]
Falta somente encontrar maneira de fazer com que a localização da cabeça não se sobreponha às outras.

**Comment by thiagobrez** [comment]
Corrigido, melhorando a responsividade.

**Comment by thiagobrez** [comment]
Tentando implementar na sidenav fixed

**Comment by thiagobrez** [comment]
Concluído alguns commits atrás.
