### ISSUE TITLE
Implementar busca por sinais no form de pesquisa

### ISSUE THREAD

**Issue by thiagobrez** [ramonrdm/glossariolibras#57]
Trabalhando em cima disso. Os imagepickers já estão funcionais, exceto cmE e cmD. Arrumar isso, aparência e modificar lógica de busca para incluir estes parâmetros.

**Comment by thiagobrez** [comment]
Conforme conversado com ramon, foi deixado somente um picker para grupoCM e CM, já que não há mão dominante. Falta somente fazer lógica de busca.

**Comment by ramonrdm** [comment]
localização nao tem como colocar nenhum.
no chrome esta muito pequeno.
problema com aliamento qndo usa as opções da sessão.

**Comment by ramonrdm** [comment]
modais nao estao presente no mobile

**Comment by thiagobrez** [comment]
Tentando corrigir bug na seleção.

**Comment by ramonrdm** [comment]
Cleberton está assumindo a issue.

**Comment by ramonrdm** [comment]
funcionando o basico
