### ISSUE TITLE
Criar e estudar grade e lista para a busca de sinais

### ISSUE THREAD

**Issue by Cleberton-Oliveira** [ramonrdm/glossariolibras#87]
Tentar incorporar imagem ou gif do sinal em ambas

**Comment by ramonrdm** [comment]
funciona, mas está faltando um polimento.
os sinais devem ficar na mesma linda de grade, padronizando o tamanho do card e dando espaço entre os cards.

**Comment by Cleberton-Oliveira** [comment]
Bug no basca grade

**Comment by ramonrdm** [comment]
necessita ajuste quando usa o scroll infinity

**Comment by BryanMLima** [comment]
O projeto foi direcionado para busca por paginação
