### ISSUE TITLE
Imagem padrão para falta de imagem/video

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/glossariolibras#9]
Colocar uma imagem padrão para quando nao tem imagem ou vídeo em um modelo, seja sinal, glossário, user, etc...
vejam se o materializecss já tem um icon ou imagem padrão para isso e a utilizem.
vc devem rever todas as páginas template e colocar essa verificação.

**Comment by thiagobrez** [comment]
Concluído, falta formatação.

**Comment by thiagobrez** [comment]
Padronizado todos os ícones para a cor azul-escura.
